package task

const (
	ErrorCodeInvalidPlan                 = "INVALID_PLAN"
	ErrorCodePlanSnapshotNotFound        = "PLAN_SNAPSHOT_NOT_FOUND"
	ErrorCodePlanTemplateNotFound        = "PLAN_TEMPLATE_NOT_FOUND"
	ErrorCodePlanTemplateRequired        = "PLAN_TEMPLATE_REQUIRED"
	ErrorCodeAttachmentContentRequired   = "ATTACHMENT_CONTENT_REQUIRED"
	ErrorCodeAttachmentMimeMismatch      = "ATTACHMENT_MIME_MISMATCH"
	ErrorCodeAttachmentNameRequired      = "ATTACHMENT_NAME_REQUIRED"
	ErrorCodeAttachmentPathNotFound      = "ATTACHMENT_PATH_NOT_FOUND"
	ErrorCodeAttachmentSizeExceeded      = "ATTACHMENT_SIZE_EXCEEDED"
	ErrorCodeAttachmentTypeUnsupported   = "ATTACHMENT_TYPE_UNSUPPORTED"
	ErrorCodeBaseBranchCreateFailed      = "BASE_BRANCH_CREATE_FAILED"
	ErrorCodeBaseBranchNotFound          = "BASE_BRANCH_NOT_FOUND"
	ErrorCodeBaseBranchRequired          = "BASE_BRANCH_REQUIRED"
	ErrorCodeDescriptionRequired         = "DESCRIPTION_REQUIRED"
	ErrorCodeExecutionAgentUnavailable   = "EXECUTION_AGENT_UNAVAILABLE"
	ErrorCodeExecutionBackendUnavailable = "EXECUTION_BACKEND_UNAVAILABLE"
	ErrorCodeInvalidAttachmentPayload    = "INVALID_ATTACHMENT_PAYLOAD"
	ErrorCodeLeadAgentInvalid            = "LEAD_AGENT_INVALID"
	ErrorCodeLeadAgentRequired           = "LEAD_AGENT_REQUIRED"
	ErrorCodeLeadAgentUnhealthy          = "LEAD_AGENT_UNHEALTHY"
	ErrorCodeProjectNotFound             = "PROJECT_NOT_FOUND"
	ErrorCodeRequirementsConfirmed       = "REQUIREMENTS_ALREADY_CONFIRMED"
	ErrorCodeSessionNotRunning           = "SESSION_NOT_RUNNING"
	ErrorCodeSubTaskActiveSession        = "SUBTASK_ACTIVE_SESSION_EXISTS"
	ErrorCodeSubTaskCancelNotAllowed     = "SUBTASK_CANCEL_NOT_ALLOWED"
	ErrorCodeSubTaskChangeAgentInvalid   = "SUBTASK_CHANGE_AGENT_NOT_ALLOWED"
	ErrorCodeSubTaskDiscardNotAllowed    = "SUBTASK_DISCARD_NOT_ALLOWED"
	ErrorCodeSubTaskNotFound             = "SUBTASK_NOT_FOUND"
	ErrorCodeSubTaskReassignNotAllowed   = "SUBTASK_REASSIGN_NOT_ALLOWED"
	ErrorCodeSubTaskReworkNotAllowed     = "SUBTASK_REWORK_NOT_ALLOWED"
	ErrorCodeSubTaskRetryNotAllowed      = "SUBTASK_RETRY_NOT_ALLOWED"
	ErrorCodeTaskNotFound                = "TASK_NOT_FOUND"
	ErrorCodeTaskBranchCleanupFailed     = "TASK_BRANCH_CLEANUP_FAILED"
	ErrorCodeTaskDeleteRequiresPause     = "TASK_DELETE_REQUIRES_PAUSE"
	ErrorCodeTaskBranchInvalid           = "TASK_BRANCH_INVALID"
	ErrorCodeTaskMessageRequired         = "TASK_MESSAGE_REQUIRED"
	ErrorCodeTaskNotClarifying           = "TASK_NOT_CLARIFYING"
	ErrorCodeTaskNotDraft                = "TASK_NOT_DRAFT"
	ErrorCodeTaskNotPlanReview           = "TASK_NOT_PLAN_REVIEW"
	ErrorCodeTaskPauseNotAllowed         = "TASK_PAUSE_NOT_ALLOWED"
	ErrorCodeTaskReplanFeedbackMissing   = "TASK_REPLAN_FEEDBACK_REQUIRED"
	ErrorCodeTaskReplanNotAllowed        = "TASK_REPLAN_NOT_ALLOWED"
	ErrorCodeTaskResumeNotAllowed        = "TASK_RESUME_NOT_ALLOWED"
	ErrorCodeTitleRequired               = "TITLE_REQUIRED"
)
